"""! @file
@brief Generates the light-scheme block of each palette's CSS. Run:
    python3 modules/theming/gen_palette_light.py [palette.css ...]

A palette defines its ramps for the dark scheme under body[data-palette="<id>"].
On a light background those shades read back to front (text-blue-300 is a pale
wash, bg-blue-900/40 a dark blot), so the light scheme partially inverts each
ramp: 50<->950, 100<->900, 200<->800, 300<->700, 400<->600, 500 stays. The
block goes under body[data-scheme="light"][data-palette="<id>"], appended to the
palette's own CSS after MARK (a re-run replaces it; the dark block is never
touched), together with a block that puts the dark values back on the dark
islands (the media stage), which stay dark in the light scheme.

Without arguments every modules/*/static/*.css holding a palette block is done.
"""
import glob
import os
import re
import sys

MARK = "/* -- light scheme: generated by modules/theming/gen_palette_light.py, do not edit below -- */"
# Elements that stay dark in the light scheme; scheme.css resets the gray / role
# variables on the same list.
ISLANDS = [".bg-black", ".inset-0.bg-black\\/90", '[id$="canvas_container"]', "#popout_canvas_wrap"]
_BLOCK = re.compile(r'body\[data-palette="([a-z0-9_-]+)"\]\s*\{([^}]*)\}')
_VAR = re.compile(r"--cim-([a-z0-9]+)-(\d+)\s*:\s*([^;]+);")


def parse(css):
    """! @brief The dark palette blocks of a stylesheet.
    @return [(palette id, {(role, shade): value})] in file order.
    """
    out = []
    for m in _BLOCK.finditer(css.split(MARK, 1)[0]):
        out.append((m.group(1), {(r, int(sh)): v.strip() for r, sh, v in _VAR.findall(m.group(2))}))
    return out


def invert(ramp):
    """! @brief Swap each shade with its mirror (50<->950 ... 500 stays); a shade whose
    mirror is missing is left out, so it falls back to the stock colour."""
    return {(r, sh): ramp[(r, 1000 - sh)] for (r, sh) in ramp if (r, 1000 - sh) in ramp}


def block(selector, ramp):
    """! @brief One CSS rule setting the ramp's variables, a line per role."""
    roles = []
    for r, _ in ramp:
        if r not in roles:
            roles.append(r)
    lines = []
    for r in roles:
        shades = sorted(sh for rr, sh in ramp if rr == r)
        lines.append("  " + " ".join(f"--cim-{r}-{sh}: {ramp[(r, sh)]};" for sh in shades))
    return selector + " {\n" + "\n".join(lines) + "\n}"


def light_css(css):
    """! @brief The generated section (MARK included) for a stylesheet, '' if it has no palette."""
    parts = []
    for pid, ramp in parse(css):
        light = f'body[data-scheme="light"][data-palette="{pid}"]'
        parts.append(block(light, invert(ramp)))
        parts.append(block(", ".join(f"{light} {i}" for i in ISLANDS), ramp))
    return (MARK + "\n" + "\n".join(parts) + "\n") if parts else ""


def update(path):
    """! @brief Replace (or append) the generated section of one palette CSS file.
    @return True when the file holds a palette block.
    """
    with open(path, encoding="utf-8") as f:
        css = f.read()
    gen = light_css(css)
    if not gen:
        return False
    head = css.split(MARK, 1)[0].rstrip("\n") + "\n"
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(head + gen)
    return True


if __name__ == "__main__":
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    paths = sys.argv[1:] or sorted(glob.glob(os.path.join(root, "*", "static", "*.css")))
    for p in paths:
        if update(p):
            print(f"updated {p}")
